### ISSUE TITLE
Integration Server Logs Missing

### ISSUE THREAD

**Issue by mpodwysocki** [thaliproject/TestDummy#35]
We need to have the logs from the integration server be logged as part of the logging process for the TestDummy project.  Sorry @obastemur we found the IP address.  Are we supposed to use port 8060 or any port but 8060?

**Comment by obastemur** [comment]
It is. The server address is given on README

**Comment by mpodwysocki** [comment]
@obastemur updated the previous message

**Comment by obastemur** [comment]
Anything but 8060
